# Generated by Django 5.1.2 on 2024-11-23 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='../default_ifhb1q', upload_to='images/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.TextField(blank=True, max_length=255)),
                ('currently_reading', models.TextField(blank=True, max_length=350)),
                ('favourite_coffee', models.TextField(blank=True, max_length=350)),
                ('pets_name', models.TextField(blank=True, max_length=350)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
