# Generated by Django 5.1.2 on 2024-11-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pets_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
