# Generated by Django 5.1.2 on 2024-11-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_ifhb1q', upload_to='images/'),
        ),
    ]
