# Generated by Django 5.1.2 on 2024-11-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0005_alter_bookreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='rating',
        ),
    ]
